models.py
from . import db

class Books(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    book_title = db.Column(db.String(256), nullable=False)
    author_name = db.Column(db.String(256), nullable=False)
    summary = db.Column(db.String(4096))

class Authors(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    author_name =db.Column(db.String(256), nullable=False)
    bio = db.Column(db.String(4096))

__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    
    # don't forget to change this before deploying.
    app.config['SECRET_KEY'] = 'dev'

    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///sqlite3'

    db.init_app(app)

    from .views import pages
    app.register_blueprint(pages)

    return app

# generating the database using SQLAlchemy.

# from unolibrary import db, create_app
# from .models import Books, Authors

# db.create_all(app=create_app())

views.py
from flask import Blueprint, render_template, request, redirect, url_for
from . import db
from .models import Books, Authors

pages = Blueprint('pages', __name__)

@pages.route('/')
def home():
    return render_template('home.html')

@pages.route('/books')
def books():
    books = Books.query.all()
    return render_template('all_books.html', books=books)

@pages.route('/authors')
def authors():
    authors = Authors.query.all()
    return render_template('all_authors.html', authors=authors)

@pages.route('/new_book')
def new_book():
    return render_template('new_book.html')

@pages.route('/new_book', methods=['POST'])
def new_book_post():
    book_title = request.form.get('book-title')
    author_name = request.form.get('author-name')
    summary = request.form.get('summary')
    
    new_book = Books(book_title = book_title, author_name = author_name, summary = summary)
    db.session.add(new_book)
    db.session.commit()

    return redirect(url_for('pages.new_book'))

@pages.route('/new_author')
def new_author():
    return render_template('new_author.html')

@pages.route('/new_author', methods=['POST'])
def new_author_post():
    author_name = request.form.get('author-name')
    bio = request.form.get('bio')
    
    new_author = Authors(author_name = author_name, bio = bio)
    db.session.add(new_author)
    db.session.commit()

    return redirect(url_for('pages.new_author'))

templates/all_authors.html
{% extends 'base.html' %}

{% block title %}All Authors{% endblock %}

{% block body %}

  <main role="main" class="container">

    <div class="intro">
      <h1>Available Authors</h1>
      <p class="lead">This are the authors currently present in our collection<br> Browse through.</p>
    </div>
      <section id="all-authors" class="all-authors-section">
          <div class="container">
              <div class="row">
                {% for author in authors %}

                  <div class="col-md-10 col-sm-10" id=paginate>
                      <div class="all-author-section text-center waves-effect">
                          <h4>{{ author.author_name }}</h4>
                          <div class="border"></div>
                          <p>{{ author.bio }}</p>
                      </div>
                  </div>
                {% endfor %}

                  
              </div><!-- /.row -->            
              
          </div><!-- /.container -->
      </section>


    </div>

  </main><!-- /.container -->

{% endblock %}

templates/all_books.html
{% extends 'base.html' %}

{% block title %}All Books{% endblock %}

{% block body %}

  <main role="main" class="container">

    <div class="intro">
      <h1>Available Books</h1>
      <p class="lead">This are the books currently present in our collection<br> Browse through.</p>
    </div>
      <section id="all-books" class="all-books-section">
          <div class="container">
              <div class="row">
                  
                  {% for book in books %}

                  <div class="col-md-10 col-sm-10" id=paginate>
                      <div class="all-book-section text-center waves-effect">
                          <h4>{{ book.book_title }} </h4>
                          <span> {{ book.author_name }}</span>
                          <div class="border"></div>
                          <p>{{ book.summary }}</p>
                      </div>
                  </div>
                  {% endfor %}

                  
              </div><!-- /.row -->            
              
          </div><!-- /.container -->
      </section>


    </div>

  </main><!-- /.container -->

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Uno-Library{% endblock %}</title>

{% block css %}

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename ='css/bootstrap.min.css') }}">

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename ='css/bootstrap-grid.min.css') }}">

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename ='css/bootstrap-reboot.min.css') }}">

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename ='css/main.css') }}">

{% endblock %}

</head>

<body>
{% block nav %}
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{{ url_for('pages.home') }}">Uno-Library</a>
 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Show all</a>
         <div class="dropdown-menu" aria-labelledby="dropdown">
          <a class="dropdown-item" href="{{ url_for('pages.books') }}">Books</a>
          <a class="dropdown-item" href="{{ url_for('pages.authors') }}">Authors</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Add new</a>
        <div class="dropdown-menu" aria-labelledby="dropdown">
          <a class="dropdown-item" href="{{ url_for('pages.new_book') }}">Books</a>
          <a class="dropdown-item" href="{{ url_for('pages.new_author') }}">Authors</a>
        </div>
      </li>
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
  </nav>
{% endblock %}

{% block body %}

  <main role="main" class="container">

    <div class="intro">
      <h1>Welcome to <span>Uno-Library</span></h1>
      <p class="lead">Uno is a library that catalogues books<br> Uno is cool.</p>


    </div>

  </main><!-- /.container -->

{% endblock %}

</body>

{% block js %}

  <script type="text/javascript" src="{{ url_for('static', filename = 'js/jquery.js') }}"></script>

  <script type="text/javascript" src="{{ url_for('static', filename = 'js/bootstrap.bundle.min.js') }}"></script>

  <script type="text/javascript" src="{{ url_for('static', filename = 'js/bootstrap.min.js') }}"></script>

{% endblock %}

</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block body %}

  <main role="main" class="container">

    <div class="intro">
      <h1>Welcome to <span>Uno-Library</span></h1>
      <p class="lead">Uno is a library that catalogues books<br> Uno is cool.</p>


    </div>

  </main><!-- /.container -->

{% endblock %}

templates/new_author.html
{% extends 'base.html' %}

{% block title %}New Author{% endblock %}

{% block body %}

  <main role="main" class="container">

    
    <div class="book-form">
      <div class="head">
      <h1>Add a new author</h1>
      <p class="lead">Fill the form below<br></p>
    </div>

      <!-- End Off-Canvas Navigation Section -->
      <form action="{{ url_for('pages.new_author_post') }}" method="POST">
      <div class="form-group">
        <label for="author-name">Author</label>
        <input type="text" class="form-control" id="author-name" name="author-name" placeholder="Name of the author">
      </div>
      <div class="form-group">
        <label for="desc">Bio</label>
        <textarea class="form-control" id="desc" name="bio" rows="10"></textarea>
      </div>
   
      <div class="addAuthorbtn">
      <button type="submit" class="btn btn-primary btn-md, active">Add Author</button>
      </div>
      
      </div>
  </form>
          
      

  </main><!-- /.container -->

{% endblock %}

templates/new_book.html
{% extends 'base.html' %}

{% block title %}New Author{% endblock %}

{% block body %}

  <main role="main" class="container">

    
    <div class="book-form">
      <div class="head">
      <h1>Add a new book</h1>
      <p class="lead">Fill the form below<br></p>
    </div>

      <!-- End Off-Canvas Navigation Section -->
      <form action="{{ url_for('pages.new_book_post') }}" method="POST">
      <div class="form-group">
        <label for="book-title">Title</label>
        <input type="text" class="form-control" id="book-title" name="book-title" placeholder="Name of the book">
      </div>
      <div class="form-group">
        <label for="author-name">Author</label>
        <input type="text" class="form-control" id="author-name" name="author-name" placeholder="Name of the author">
      </div>
      <div class="form-group">
        <label for="desc">Summary</label>
        <textarea class="form-control" id="desc" name="summary" rows="5"></textarea>
      </div>
   
      <div class="addBookbtn">
      <button type="submit" class="btn btn-primary btn-md, active">Add Book</button>
      </div>
  </form>
          
      

  </main><!-- /.container -->
  
{% endblock %}